name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy theme to Shopify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Shopify
        uses: shopify/github-deploy-theme@v1.0
        with:
          store: ${{ secrets.SHOPIFY_STORE_URL }}
          password: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          theme-id: ${{ secrets.SHOPIFY_THEME_ID }}
